[package]
name = "ruches"
version = "0.1.0"
edition = "2024"
authors = ["Milan Garnier"]

[dependencies]

static_assertions = "1.1.0"

futures = "0.3"
tokio = { version = "1.42", features = ["full"] }

once_cell = "1.20"

[profile.release]
debug = true